class MTSwingMeasurementDataEntity {
  late double impactHeadSpeed;
  late double impactGripSpeed;
  late double maxHeadSpeed;
  late double maxGripSpeed;
  late double impactFaceAngle;
  late int impactFaceAngleType;
  late double impactRelativeFaceAngle;
  late double impactClubPath;
  late int impactClubPathType;
  late double impactAttackAngle;
  late int impactAttackAngleType;
  late double impactLoftAngle;
  late double impactShaftRotation;
  late double downSwingShaftRotationMin;
  late double downSwingShaftRotationMax;
  late double addressLieAngle;
  late double impactLieAngle;
  late double naturalUncock;
  late double naturalReleaseTiming;
  late double swingTempo;
  late double estimateCarry;
  late double impactPointX;
  late int impactPointXType;
  late double impactPointY;
  late int impactPointYType;
  late double halfwaybackFaceAngleToVertical;
  late double topFaceAngleToHorizontal;
  late double halfwaydownFaceAngleToVertical;
  late double impactHandFirst;
  late double addressHandFirst;
  late int swingHandedType;

  MTSwingMeasurementDataEntity() {
    impactHeadSpeed = 0.0;
    impactGripSpeed = 0.0;
    maxHeadSpeed = 0.0;
    maxGripSpeed = 0.0;
    impactFaceAngle = 0.0;
    impactFaceAngleType = 1;
    impactRelativeFaceAngle = 0.0;
    impactClubPath = 0.0;
    impactClubPathType = 1;
    impactAttackAngle = 0.0;
    impactAttackAngleType = 1;
    impactLoftAngle = 0.0;
    impactShaftRotation = 0.0;
    downSwingShaftRotationMin = 0.0;
    downSwingShaftRotationMax = 0.0;
    addressLieAngle = 0.0;
    impactLieAngle = 0.0;
    naturalUncock = 0.0;
    naturalReleaseTiming = 0.0;
    swingTempo = 0.0;
    estimateCarry = 0.0;
    impactPointX = 0.0;
    impactPointXType = 1;
    impactPointY = 0.0;
    impactPointYType = 0;
    halfwaybackFaceAngleToVertical = 0.0;
    topFaceAngleToHorizontal = 0.0;
    halfwaydownFaceAngleToVertical = 0.0;
    impactHandFirst = 0.0;
    addressHandFirst = 0.0;
    swingHandedType = 0;
  }

  MTSwingMeasurementDataEntity.fromMap(final Map<String, dynamic> map) {
    impactHeadSpeed = map.containsKey("impactHeadSpeed") ? double.parse(map["impactHeadSpeed"].toString()) : 0.0;
    impactGripSpeed = map.containsKey("impactGripSpeed") ? double.parse(map["impactGripSpeed"].toString()) : 0.0;
    maxHeadSpeed = map.containsKey("maxHeadSpeed") ? double.parse(map["maxHeadSpeed"].toString()) : 0.0;
    maxGripSpeed = map.containsKey("maxGripSpeed") ? double.parse(map["maxGripSpeed"].toString()) : 0.0;
    impactFaceAngle = map.containsKey("impactFaceAngle") ? double.parse(map["impactFaceAngle"].toString()) : 0.0;
    impactFaceAngleType = map.containsKey("impactFaceAngleType") ? int.parse(map["impactFaceAngleType"].toString()) : 1;
    impactRelativeFaceAngle = map.containsKey("impactRelativeFaceAngle") ? double.parse(map["impactRelativeFaceAngle"].toString()) : 0.0;
    impactClubPath = map.containsKey("impactClubPath") ? double.parse(map["impactClubPath"].toString()) : 0.0;
    impactClubPathType = map.containsKey("impactClubPathType") ? int.parse(map["impactClubPathType"].toString()) : 1;
    impactAttackAngle = map.containsKey("impactAttackAngle") ? double.parse(map["impactAttackAngle"].toString()) : 0.0;
    impactAttackAngleType = map.containsKey("impactAttackAngleType") ? int.parse(map["impactAttackAngleType"].toString()) : 1;
    impactLoftAngle = map.containsKey("impactLoftAngle") ? double.parse(map["impactLoftAngle"].toString()) : 0.0;
    impactShaftRotation = map.containsKey("impactShaftRotation") ? double.parse(map["impactShaftRotation"].toString()) : 0.0;
    downSwingShaftRotationMin = map.containsKey("downSwingShaftRotationMin") ? double.parse(map["downSwingShaftRotationMin"].toString()) : 0.0;
    downSwingShaftRotationMax = map.containsKey("downSwingShaftRotationMaxdownSwingShaftRotationMax") ? double.parse(map[""].toString()) : 0.0;
    addressLieAngle = map.containsKey("addressLieAngle") ? double.parse(map["addressLieAngle"].toString()) : 0.0;
    impactLieAngle = map.containsKey("impactLieAngle") ? double.parse(map["impactLieAngle"].toString()) : 0.0;
    naturalUncock = map.containsKey("naturalUncock") ? double.parse(map["naturalUncock"].toString()) : 0.0;
    naturalReleaseTiming = map.containsKey("naturalReleaseTiming") ? double.parse(map["naturalReleaseTiming"].toString()) : 0.0;
    swingTempo = map.containsKey("swingTempo") ? double.parse(map["swingTempo"].toString()) : 0.0;
    estimateCarry = map.containsKey("estimateCarry") ? double.parse(map["estimateCarry"].toString()) : 0.0;
    impactPointX = map.containsKey("impactPointX") ? double.parse(map["impactPointX"].toString()) : 0.0;
    impactPointXType = map.containsKey("impactPointXType") ? int.parse(map["impactPointXType"].toString()) : 1;
    impactPointY = map.containsKey("impactPointY") ? double.parse(map["impactPointY"].toString()) : 0.0;
    impactPointYType = map.containsKey("impactPointYType") ? int.parse(map["impactPointYType"].toString()) : 0;
    halfwaybackFaceAngleToVertical = map.containsKey("halfwaybackFaceAngleToVertical") ? double.parse(map["halfwaybackFaceAngleToVertical"].toString()) : 0.0;
    topFaceAngleToHorizontal = map.containsKey("topFaceAngleToHorizontal") ? double.parse(map["topFaceAngleToHorizontal"].toString()) : 0.0;
    halfwaydownFaceAngleToVertical = map.containsKey("halfwaydownFaceAngleToVertical") ? double.parse(map["halfwaydownFaceAngleToVertical"].toString()) : 0.0;
    impactHandFirst = map.containsKey("impactHandFirst") ? double.parse(map["impactHandFirst"].toString()) : 0.0;
    addressHandFirst = map.containsKey("addressHandFirst") ? double.parse(map["addressHandFirst"].toString()) : 0.0;
    swingHandedType = map.containsKey("swingHandedType") ? int.parse(map["swingHandedType"].toString()) : 0;
  }
}
